name: minecraft-server
services:
  proxy:
    image: docker.io/nginx:1.25.4
    profiles:
      - vanilla
      - paper
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./proxy/templates/default.conf.template
        target: /etc/nginx/templates/default.conf.template
        read_only: true
  minecraft-vanilla:
    tty: true
    stdin_open: true
    build:
      context: ./minecraft-vanilla
      dockerfile: Dockerfile
    profiles:
      - vanilla
    ports:
      - 25565:25565
    environment:
      TZ: ${TZ}
      VERSION: ${VERSION:-latest}
      MEMORY: ${MEMORY}
    volumes:
      - type: bind
        source: ./minecraft-vanilla/banned-ips.json
        target: /root/banned-ips.json
      - type: bind
        source: ./minecraft-vanilla/banned-players.json
        target: /root/banned-players.json
      - type: bind
        source: ./minecraft-vanilla/eula.txt
        target: /root/eula.txt
      - type: bind
        source: ./minecraft-vanilla/ops.json
        target: /root/ops.json
      - type: bind
        source: ./minecraft-vanilla/server.properties
        target: /root/server.properties
      - type: bind
        source: ./minecraft-vanilla/whitelist.json
        target: /root/whitelist.json
      - type: bind
        source: ./minecraft-vanilla/world
        target: /root/world
      - type: bind
        source: ./minecraft-vanilla/backup
        target: /root/backup
      - type: bind
        source: ./minecraft-vanilla/scripts
        target: /root/scripts
  minecraft-paper:
    tty: true
    stdin_open: true
    build:
      context: ./minecraft-paper
      dockerfile: Dockerfile
    profiles:
      - paper
    ports:
      - 25565:25565
    environment:
      TZ: ${TZ}
      VERSION: ${VERSION:-latest}
      PAPER_BUILD: ${PAPER_BUILD:-latest}
      MEMORY: ${MEMORY}
    volumes:
      - type: bind
        source: ./minecraft-paper/banned-ips.json
        target: /root/banned-ips.json
      - type: bind
        source: ./minecraft-paper/banned-players.json
        target: /root/banned-players.json
      - type: bind
        source: ./minecraft-paper/eula.txt
        target: /root/eula.txt
      - type: bind
        source: ./minecraft-paper/ops.json
        target: /root/ops.json
      - type: bind
        source: ./minecraft-paper/server.properties
        target: /root/server.properties
      - type: bind
        source: ./minecraft-paper/whitelist.json
        target: /root/whitelist.json
      - type: bind
        source: ./minecraft-paper/world
        target: /root/world
      - type: bind
        source: ./minecraft-paper/world_nether
        target: /root/world_nether
      - type: bind
        source: ./minecraft-paper/world_the_end
        target: /root/world_the_end
      - type: bind
        source: ./minecraft-paper/plugins
        target: /root/plugins
      - type: bind
        source: ./minecraft-paper/backup
        target: /root/backup
      - type: bind
        source: ./minecraft-paper/scripts
        target: /root/scripts
      - type: bind
        source: ./minecraft-paper/bukkit.yml
        target: /root/bukkit.yml
      - type: bind
        source: ./minecraft-paper/commands.yml
        target: /root/commands.yml
      - type: bind
        source: ./minecraft-paper/help.yml
        target: /root/help.yml
      - type: bind
        source: ./minecraft-paper/permissions.yml
        target: /root/permissions.yml
      - type: bind
        source: ./minecraft-paper/spigot.yml
        target: /root/spigot.yml
      - type: bind
        source: ./minecraft-paper/config
        target: /root/config
  client:
    restart: no
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        MCC_VERSION: ${MCC_VERSION}
        MCC_ARCH: ${MCC_ARCH}
    profiles:
      - client
    volumes:
      - type: bind
        source: ./client/data
        target: /opt/data
  rcon:
    restart: no
    build:
      context: ./rcon
      dockerfile: Dockerfile
    profiles:
      - rcon
    environment:
      MCRCON_HOST: ${MCRCON_HOST}
      MCRCON_PORT: ${MCRCON_PORT}
      MCRCON_PASS: ${MCRCON_PASS}
