name: minecraft-server
services:
  minecraft:
    container_name: minecraft
    tty: true
    stdin_open: true
    restart: always
    build:
      context: ./minecraft
      dockerfile: Dockerfile
    ports:
      - 25565:25565
    environment:
      TZ: ${TZ}
      MEMORY: ${MEMORY}
    volumes:
      - type: bind
        source: ./minecraft/banned-ips.json
        target: /root/banned-ips.json
      - type: bind
        source: ./minecraft/banned-players.json
        target: /root/banned-players.json
      - type: bind
        source: ./minecraft/eula.txt
        target: /root/eula.txt
      - type: bind
        source: ./minecraft/ops.json
        target: /root/ops.json
      - type: bind
        source: ./minecraft/server.properties
        target: /root/server.properties
      - type: bind
        source: ./minecraft/whitelist.json
        target: /root/whitelist.json
      - type: bind
        source: ./minecraft/world
        target: /root/world
      - type: bind
        source: ./minecraft/backup
        target: /root/backup
      - type: bind
        source: ./minecraft/scripts
        target: /root/scripts
  rcon:
    container_name: rcon
    restart: no
    build:
      context: ./rcon
      dockerfile: Dockerfile
    environment:
      MCRCON_PORT: ${MCRCON_PORT}
      MCRCON_PASS: ${MCRCON_PASS}
