name: minecraft-server
services:
  minecraft-vanilla:
    tty: true
    stdin_open: true
    build:
      context: ./minecraft-vanilla
      dockerfile: Dockerfile
    profiles:
      - vanilla
    ports:
      - 25565:25565
    environment:
      TZ: ${TZ}
      VERSION: ${VERSION:-latest}
      MEMORY: ${MEMORY}
    volumes:
      - type: bind
        source: ./minecraft-vanilla/banned-ips.json
        target: /root/banned-ips.json
      - type: bind
        source: ./minecraft-vanilla/banned-players.json
        target: /root/banned-players.json
      - type: bind
        source: ./minecraft-vanilla/eula.txt
        target: /root/eula.txt
      - type: bind
        source: ./minecraft-vanilla/ops.json
        target: /root/ops.json
      - type: bind
        source: ./minecraft-vanilla/server.properties
        target: /root/server.properties
      - type: bind
        source: ./minecraft-vanilla/whitelist.json
        target: /root/whitelist.json
      - type: bind
        source: ./minecraft-vanilla/world
        target: /root/world
      - type: bind
        source: ./minecraft-vanilla/backup
        target: /root/backup
      - type: bind
        source: ./minecraft-vanilla/scripts
        target: /root/scripts
  rcon:
    restart: no
    build:
      context: ./rcon
      dockerfile: Dockerfile
    profiles:
      - rcon
    environment:
      MCRCON_HOST: ${MCRCON_HOST}
      MCRCON_PORT: ${MCRCON_PORT}
      MCRCON_PASS: ${MCRCON_PASS}
